---
apiVersion: batch/v1
kind: Job
metadata:
  name: buildah-build
spec:
  completions: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  template:
    spec:
      volumes:
        - name: src-dir
          persistentVolumeClaim:
            claimName: shared-data-pvc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - image: quay.io/buildah/stable
          name: buildah
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: src-dir
              mountPath: /hello-http
              subPath: hello-http
          env:
            - name: ECR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecr-secret
                  key: password
          workingDir: /hello-http
          args:
            - "./buildah-build.sh"
      restartPolicy: Never
