apiVersion: batch/v1
kind: Job
metadata:
  name: buildah-build
spec:
  completions: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      volumes:
        - name: src-dir
          persistentVolumeClaim:
            claimName: shared-data-pvc
      containers:
      - image: quay.io/buildah/stable
        name: buildah
        securityContext:
          privileged: true
        volumeMounts:
          - name: src-dir
            mountPath: /hello-http
            subPath: hello-http
        workingDir: /hello-http
        args:
          - "./buildah-build.sh"
      restartPolicy: Never
