---
apiVersion: batch/v1
kind: Job
metadata:
  name: buildah-build
spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    spec:
      volumes:
        - name: src-dir
          emptyDir:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: git
          image: alpine/git
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: src-dir
              mountPath: /git
          args:
            - "clone"
            - "--depth"
            - "1"
            - "--branch"
            - "main"
            - "http://github.com/ptorre/hello-http"
      containers:
        - image: quay.io/buildah/stable
          name: buildah
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: src-dir
              mountPath: /hello-http
              subPath: hello-http
          env:
            - name: ECR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecr-secret
                  key: password
          workingDir: /hello-http
          args:
            - "./buildah-build.sh"
      restartPolicy: Never
