# This is a basic workflow to enable triggering from other branches

name: Manual workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: echo "Hello ${{ github.event.inputs.name }}"
