---
name: Build main branch

on:
  workflow_dispatch: null
  workflow_call:
    outputs:
      image:
        description: 'Name of the image built'
        value: ${{ jobs.build-hello-http.outputs.image }}
      tags:
        description: 'List of the tags that were created, separated by spaces'
        value: ${{ jobs.build-hello-http.outputs.tags }}
      image-with-tag:
        description: 'Name of the image tagged with the first tag present'
        value: ${{ jobs.build-hello-http.outputs.image-with-tag }}
      registry-path:
        description: 'Registry paths to which the was pushed'
        value: ${{ jobs.build-hello-http.outputs.registry-path }}

permissions: read-all

jobs:
  build-hello-http:
    name: Build image using biuldah
    runs-on: ubuntu-20.04
    permissions:
      packages: write

    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
    outputs:
      image: ${{ steps.build_image.outputs.image }}
      tags: ${{ steps.build_image.outputs.tags }}
      image-with-tag: ${{ steps.build_image.outputs.image-with-tag }}
      registry-path: ${{ steps.push-to-ghcr.outputs.registry-path }}

    steps:

      - name: Install qemu dependency
        id: install_qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2.10
        with:
          image: ${{ github.event.repository.name }}
          tags: ${{ github.sha }}
          archs: arm64, amd64
          containerfiles: ./Containerfile
          labels: |
            org.opencontainers.image.title=Simple http hello server
            org.opencontainers.image.description=Simple python based http server for kubernetes testing.
            org.opencontainers.image.licenses=Apache-2.0
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build Outputs
        run: |
          echo "Image: ${{ steps.build_image.outputs.image }}"
          echo "Tags: ${{ steps.build_image.outputs.tags }}"
          echo "Tagged Image: ${{ steps.build_image.outputs.image-with-tag }}"

      - name: Inspect manifest
        run:
          buildah manifest inspect
          ${{ steps.build_image.outputs.image-with-tag }}

      - name: Push To ghcr.io
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io/${{ github.repository_owner }}
          image: ${{ steps.build_image.outputs.image }}
          tags: latest ${{ steps.build_image.outputs.tags }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run:
          echo
          "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
