---
name: Build main branch

on:
  workflow_dispatch: null

jobs:
  build-hello-http:
    name: Build image using biuldah
    env:
      IMAGE_NAME: hello-http
      IMAGE_TAG: latest
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false

    steps:

      - name: Install qemu dependency
        id: install_qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build Image
        id: build_image_multiarch
        uses: redhat-actions/buildah-build@v2.10
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }} ${{ github.sha }}
          oci: true
          archs: arm64, amd64
          containerfiles: ./Containerfile
          labels: |
            "org.opencontainers.image.title"="Simple http hello server"
            "org.opencontainers.image.description"="Simple python based http server for kubernetes testing."
            "org.opencontainers.image.licenses"="Apache-2.0"
            "org.opencontainers.image.version"="v0.0.0"
            "org.opencontainers.image.revision"=${{ github.sha }}

      - name: Echo Outputs
        run: |
          echo "Image: ${{ steps.build_image_multiarch.outputs.image }}"
          echo "Tags: ${{ steps.build_image_multiarch.outputs.tags }}"
          echo "Tagged Image: ${{ steps.build_image_multiarch.outputs.image-with-tag }}"

      - name: Inspect manifest
        run:
          buildah manifest inspect
          ${{ steps.build_image_multiarch.outputs.image }}:${{ env.IMAGE_TAG }}
