---
name: Release and push to ghcr registry

on:
  workflow_dispatch: null

jobs:
  tag-image-with-release-version:
    name: Tag image with release version
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - name: Inspect manifest for the github sha of this build
        run:
          buildah manifest inspect
          docker://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
